/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  varchar,
  timestamp,
  numeric,
  boolean,
  serial,
  integer,
  jsonb,
  pgEnum,
} from "@payloadcms/db-vercel-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-vercel-postgres/drizzle";
export const enum_app_users_role = pgEnum("enum_app_users_role", [
  "coach",
  "staff",
  "player",
  "visitor",
]);

export const admins = pgTable(
  "admins",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fullname: varchar("fullname").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    admins_updated_at_idx: index("admins_updated_at_idx").on(columns.updatedAt),
    admins_created_at_idx: index("admins_created_at_idx").on(columns.createdAt),
    admins_email_idx: uniqueIndex("admins_email_idx").on(columns.email),
  }),
);

export const media = pgTable(
  "media",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    alt: varchar("alt").notNull(),
    prefix: varchar("prefix").default("media-simply-life"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
  }),
);

export const app_users = pgTable(
  "app_users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    lastname: varchar("lastname").notNull(),
    firstname: varchar("firstname").notNull(),
    role: enum_app_users_role("role").notNull().default("player"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    app_users_updated_at_idx: index("app_users_updated_at_idx").on(
      columns.updatedAt,
    ),
    app_users_created_at_idx: index("app_users_created_at_idx").on(
      columns.createdAt,
    ),
    app_users_email_idx: uniqueIndex("app_users_email_idx").on(columns.email),
  }),
);

export const sponsors = pgTable(
  "sponsors",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    logo: uuid("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    category: uuid("category_id")
      .notNull()
      .references(() => sponsor_categories.id, {
        onDelete: "set null",
      }),
    phone: varchar("phone"),
    website: varchar("website"),
    address: varchar("address"),
    latitude: numeric("latitude"),
    longitude: numeric("longitude"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    sponsors_logo_idx: index("sponsors_logo_idx").on(columns.logo),
    sponsors_category_idx: index("sponsors_category_idx").on(columns.category),
    sponsors_updated_at_idx: index("sponsors_updated_at_idx").on(
      columns.updatedAt,
    ),
    sponsors_created_at_idx: index("sponsors_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const sponsor_categories = pgTable(
  "sponsor_categories",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    sponsor_categories_updated_at_idx: index(
      "sponsor_categories_updated_at_idx",
    ).on(columns.updatedAt),
    sponsor_categories_created_at_idx: index(
      "sponsor_categories_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const chat_rooms = pgTable(
  "chat_rooms",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    app_user: uuid("app_user_id")
      .notNull()
      .references(() => app_users.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    description: varchar("description"),
    color: varchar("color"),
    category: varchar("category"),
    private: boolean("private"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    chat_rooms_app_user_idx: index("chat_rooms_app_user_idx").on(
      columns.app_user,
    ),
    chat_rooms_updated_at_idx: index("chat_rooms_updated_at_idx").on(
      columns.updatedAt,
    ),
    chat_rooms_created_at_idx: index("chat_rooms_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const signatures = pgTable(
  "signatures",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    app_user: uuid("app_user_id")
      .notNull()
      .references(() => app_users.id, {
        onDelete: "set null",
      }),
    file: uuid("file_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    signatures_app_user_idx: index("signatures_app_user_idx").on(
      columns.app_user,
    ),
    signatures_file_idx: index("signatures_file_idx").on(columns.file),
    signatures_updated_at_idx: index("signatures_updated_at_idx").on(
      columns.updatedAt,
    ),
    signatures_created_at_idx: index("signatures_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const messages = pgTable(
  "messages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    app_user: uuid("app_user_id")
      .notNull()
      .references(() => app_users.id, {
        onDelete: "set null",
      }),
    chat_room: uuid("chat_room_id")
      .notNull()
      .references(() => chat_rooms.id, {
        onDelete: "set null",
      }),
    message: varchar("message").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    messages_app_user_idx: index("messages_app_user_idx").on(columns.app_user),
    messages_chat_room_idx: index("messages_chat_room_idx").on(
      columns.chat_room,
    ),
    messages_updated_at_idx: index("messages_updated_at_idx").on(
      columns.updatedAt,
    ),
    messages_created_at_idx: index("messages_created_at_idx").on(
      columns.createdAt,
    ),
  }),
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx",
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx",
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    adminsID: uuid("admins_id"),
    mediaID: uuid("media_id"),
    "app-usersID": uuid("app_users_id"),
    sponsorsID: uuid("sponsors_id"),
    "sponsor-categoriesID": uuid("sponsor_categories_id"),
    "chat-roomsID": uuid("chat_rooms_id"),
    signaturesID: uuid("signatures_id"),
    messagesID: uuid("messages_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent,
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_admins_id_idx: index(
      "payload_locked_documents_rels_admins_id_idx",
    ).on(columns.adminsID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx",
    ).on(columns.mediaID),
    payload_locked_documents_rels_app_users_id_idx: index(
      "payload_locked_documents_rels_app_users_id_idx",
    ).on(columns["app-usersID"]),
    payload_locked_documents_rels_sponsors_id_idx: index(
      "payload_locked_documents_rels_sponsors_id_idx",
    ).on(columns.sponsorsID),
    payload_locked_documents_rels_sponsor_categories_id_idx: index(
      "payload_locked_documents_rels_sponsor_categories_id_idx",
    ).on(columns["sponsor-categoriesID"]),
    payload_locked_documents_rels_chat_rooms_id_idx: index(
      "payload_locked_documents_rels_chat_rooms_id_idx",
    ).on(columns["chat-roomsID"]),
    payload_locked_documents_rels_signatures_id_idx: index(
      "payload_locked_documents_rels_signatures_id_idx",
    ).on(columns.signaturesID),
    payload_locked_documents_rels_messages_id_idx: index(
      "payload_locked_documents_rels_messages_id_idx",
    ).on(columns.messagesID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    adminsIdFk: foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_locked_documents_rels_admins_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    "app-usersIdFk": foreignKey({
      columns: [columns["app-usersID"]],
      foreignColumns: [app_users.id],
      name: "payload_locked_documents_rels_app_users_fk",
    }).onDelete("cascade"),
    sponsorsIdFk: foreignKey({
      columns: [columns["sponsorsID"]],
      foreignColumns: [sponsors.id],
      name: "payload_locked_documents_rels_sponsors_fk",
    }).onDelete("cascade"),
    "sponsor-categoriesIdFk": foreignKey({
      columns: [columns["sponsor-categoriesID"]],
      foreignColumns: [sponsor_categories.id],
      name: "payload_locked_documents_rels_sponsor_categories_fk",
    }).onDelete("cascade"),
    "chat-roomsIdFk": foreignKey({
      columns: [columns["chat-roomsID"]],
      foreignColumns: [chat_rooms.id],
      name: "payload_locked_documents_rels_chat_rooms_fk",
    }).onDelete("cascade"),
    signaturesIdFk: foreignKey({
      columns: [columns["signaturesID"]],
      foreignColumns: [signatures.id],
      name: "payload_locked_documents_rels_signatures_fk",
    }).onDelete("cascade"),
    messagesIdFk: foreignKey({
      columns: [columns["messagesID"]],
      foreignColumns: [messages.id],
      name: "payload_locked_documents_rels_messages_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key,
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx",
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    adminsID: uuid("admins_id"),
    "app-usersID": uuid("app_users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_admins_id_idx: index(
      "payload_preferences_rels_admins_id_idx",
    ).on(columns.adminsID),
    payload_preferences_rels_app_users_id_idx: index(
      "payload_preferences_rels_app_users_id_idx",
    ).on(columns["app-usersID"]),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    adminsIdFk: foreignKey({
      columns: [columns["adminsID"]],
      foreignColumns: [admins.id],
      name: "payload_preferences_rels_admins_fk",
    }).onDelete("cascade"),
    "app-usersIdFk": foreignKey({
      columns: [columns["app-usersID"]],
      foreignColumns: [app_users.id],
      name: "payload_preferences_rels_app_users_fk",
    }).onDelete("cascade"),
  }),
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx",
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx",
    ).on(columns.createdAt),
  }),
);

export const relations_admins = relations(admins, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_app_users = relations(app_users, () => ({}));
export const relations_sponsors = relations(sponsors, ({ one }) => ({
  logo: one(media, {
    fields: [sponsors.logo],
    references: [media.id],
    relationName: "logo",
  }),
  category: one(sponsor_categories, {
    fields: [sponsors.category],
    references: [sponsor_categories.id],
    relationName: "category",
  }),
}));
export const relations_sponsor_categories = relations(
  sponsor_categories,
  () => ({}),
);
export const relations_chat_rooms = relations(chat_rooms, ({ one }) => ({
  app_user: one(app_users, {
    fields: [chat_rooms.app_user],
    references: [app_users.id],
    relationName: "app_user",
  }),
}));
export const relations_signatures = relations(signatures, ({ one }) => ({
  app_user: one(app_users, {
    fields: [signatures.app_user],
    references: [app_users.id],
    relationName: "app_user",
  }),
  file: one(media, {
    fields: [signatures.file],
    references: [media.id],
    relationName: "file",
  }),
}));
export const relations_messages = relations(messages, ({ one }) => ({
  app_user: one(app_users, {
    fields: [messages.app_user],
    references: [app_users.id],
    relationName: "app_user",
  }),
  chat_room: one(chat_rooms, {
    fields: [messages.chat_room],
    references: [chat_rooms.id],
    relationName: "chat_room",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_locked_documents_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "app-usersID": one(app_users, {
      fields: [payload_locked_documents_rels["app-usersID"]],
      references: [app_users.id],
      relationName: "app-users",
    }),
    sponsorsID: one(sponsors, {
      fields: [payload_locked_documents_rels.sponsorsID],
      references: [sponsors.id],
      relationName: "sponsors",
    }),
    "sponsor-categoriesID": one(sponsor_categories, {
      fields: [payload_locked_documents_rels["sponsor-categoriesID"]],
      references: [sponsor_categories.id],
      relationName: "sponsor-categories",
    }),
    "chat-roomsID": one(chat_rooms, {
      fields: [payload_locked_documents_rels["chat-roomsID"]],
      references: [chat_rooms.id],
      relationName: "chat-rooms",
    }),
    signaturesID: one(signatures, {
      fields: [payload_locked_documents_rels.signaturesID],
      references: [signatures.id],
      relationName: "signatures",
    }),
    messagesID: one(messages, {
      fields: [payload_locked_documents_rels.messagesID],
      references: [messages.id],
      relationName: "messages",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    adminsID: one(admins, {
      fields: [payload_preferences_rels.adminsID],
      references: [admins.id],
      relationName: "admins",
    }),
    "app-usersID": one(app_users, {
      fields: [payload_preferences_rels["app-usersID"]],
      references: [app_users.id],
      relationName: "app-users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_app_users_role: typeof enum_app_users_role;
  admins: typeof admins;
  media: typeof media;
  app_users: typeof app_users;
  sponsors: typeof sponsors;
  sponsor_categories: typeof sponsor_categories;
  chat_rooms: typeof chat_rooms;
  signatures: typeof signatures;
  messages: typeof messages;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_admins: typeof relations_admins;
  relations_media: typeof relations_media;
  relations_app_users: typeof relations_app_users;
  relations_sponsors: typeof relations_sponsors;
  relations_sponsor_categories: typeof relations_sponsor_categories;
  relations_chat_rooms: typeof relations_chat_rooms;
  relations_signatures: typeof relations_signatures;
  relations_messages: typeof relations_messages;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-vercel-postgres/types" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
